pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Policy Evaluation') {
            steps {
                nexusPolicyEvaluation iqApplication: extractProjectName(), iqStage: env.GIT_BRANCH == 'master' ? 'build': 'develop'
            }
        }
    }
}

// This function extracts the project name from the GIT_URL environment variable.
def extractProjectName() {
    def match = env.GIT_URL =~ /.+\/([^\/]+)\.git/
    return match[0][1]
}
