name: Evaluate Workflow

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Sonatype Evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          username: ${{ secrets.ITSA_USERNAME }}
          password: ${{ secrets.ITSA_PASSWORD }}
          iq-server-url: https://int-test.sonatype.app/platform/
          application-id: et-app
          stage: build
          scan-targets: target/*.jar
