name: Evaluate Workflow

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Determine IQ Stage
        run: |
          [ "$GITHUB_REF_NAME" = "master" ] && IQ_STAGE="build" || IQ_STAGE="develop"
          echo "IQ_STAGE=${IQ_STAGE}"
          echo "IQ_STAGE=${IQ_STAGE}" >> $GITHUB_ENV

      - name: Determine Repository Name
        run: |          
          repo_name="${GITHUB_REPOSITORY#*/}"
          echo "IQ_APP_ID=${repo_name}"
          echo "IQ_APP_ID=${repo_name}" >> $GITHUB_ENV

      - name: Sonatype Evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          username: ${{ secrets.ITSA_USERNAME }}
          password: ${{ secrets.ITSA_PASSWORD }}
          iq-server-url: https://int-test.sonatype.app/platform/
          application-id: ${{ env.IQ_APP_ID }}
          stage: ${{ env.IQ_STAGE }}
          scan-targets: target/*.jar
